version: "3.7"
services: 
  mongodb:
    restart: unless-stopped
    image: mongo
    container_name: graylog_mongodb
  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: graylog_elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 512m
  graylog:
    restart: unless-stopped
    image: graylog/graylog:3.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=XnNCPNhC+b+8xqN826%5
      # Password: P@ssw0rd
      - GRAYLOG_ROOT_PASSWORD_SHA2=B03DDF3CA2E714A6548E7495E2A03F5E824EAAC9837CD7F159C67B90FB4B7342
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9900/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9900:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp